FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./cmd/webapp

FROM alpine:latest
# FROM amd64/alpine:lastest
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080
ENV PORT=8080
ENV AWS_DEFAULT_REGION=us-west-2
ENV HOSTNAME=
CMD ["./main"]